spring:
  datasource:
    url: jdbc:mysql://${e2cef.datasource.ip}:3306/zenofsword-car?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: ${e2cef.datasource.username}
    password: ${e2cef.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: course.linkflower.link.oneframework.common.model
  global-config:
    db-config:
      id-type: auto

e2cef: